spring:
  application:
     name: spot-service
  data:
    mongodb:
      database: spot
      host: localhost

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker-compose
  application:
     name: spot-service
  data:
    mongodb:
      database: spot
      host: mongo

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/